spring: # ??? ?? ??
  profiles: # ??? ??, ?? ???? ???? ?????.
    active: dev # 'dev' ???? ?? ????? ????.

  datasource: # ??? ??? ?? ??
    driver-class-name: org.mariadb.jdbc.Driver # MariaDB? JDBC ????? ??? ?????.
    url: jdbc:mariadb://127.0.0.1:3306/gram_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    # MariaDB ??????? ???? ?? URL???. ???? ??, ?? ???, ?? ??? ? ?? ???? ?? ?? ??? ???? ????.
    username: root # ?????? ??? ???? ??? ?????.
    password:  # ?????? ??? ???? ?????.

  jpa: # Java Persistence API (JPA)? ?? ??
    hibernate: # Hibernate, JPA ??? ?? ??
      ddl-auto: create # Hibernate? ??? ??? ???? ?????? ???? ???? ????? ?????. ?? ???? ??? ? ???? ???? ????? ??? ? ????.
    properties: # Hibernate? ?? ?? ??
      hibernate: # ?? Hibernate ??
        show_sql: true # SQL ?? ??? ???? ??? ?????. ???? ?????.
        format_sql: true # ???? ?? SQL ?? ???? ??? ?????. ???? ??? ?????.
        use_sql_comments: true # ??? SQL? ??? ???? ??? ?????. ??? SQL? ???? ? ??? ???.
logging: # ??? ?? ??
  level: # ?? ??? ?? ???? ?? ?? ??? ?????.
    root: INFO # ?? ???? ?? ??? INFO? ?????.
    com.ll.gramgram_ai: DEBUG # 'com.ll.gramgram_ai' ???? ?? ??? DEBUG? ?????.
    org.hibernate.orm.jdbc.bind: TRACE # 'org.hibernate.orm.jdbc.bind' ???? ?? ??? TRACE? ?????.
    org.hibernate.orm.jdbc.extract: TRACE # 'org.hibernate.orm.jdbc.extract' ???? ?? ??? TRACE? ?????.
